### ISSUE TITLE
ERROR: ccall: could not find function opensmt_mk_num in library libdreal

### ISSUE THREAD

**Issue by evanthebouncy** [dreal/DReal.jl#11]
julia> using dReal

julia> x = Var(Int,"x")
Ex{Int64}(Ptr{Void} @0x00000000078b1ec0,Set{ASCIIString}({"x"}))

julia> y = Var(Int,"y")
Ex{Int64}(Ptr{Void} @0x000000000727ae30,Set{ASCIIString}({"y"}))

julia> add!((x > 2) & (y < 10) & (x + 2*y == 7))
ERROR: ccall: could not find function opensmt_mk_num in library libdreal
 in > at /home/evan/.julia/v0.3/dReal/src/construct.jl:32
 in > at /home/evan/.julia/v0.3/dReal/src/construct.jl:41

**Comment by soonhokong** [comment]
@evanthebouncy, thanks for the report. 

I guess you downloaded dReal shared libraries from the link. We recently added `opensmt_mk_num` to the codebase, but didn't released it yet. I'll do it now and let you know with another comment.

**Comment by evanthebouncy** [comment]
fastest reply on a github issue i've ever seen. thanks and do let me know.

**Comment by soonhokong** [comment]
@evanthebouncy, I just release a new version at https://github.com/dreal/dreal3/releases/tag/v3.15.06. I also updated the instructions at https://github.com/dreal/dReal.jl/blob/master/README.md.

Please download the new release and update your existing dreal shared libraries. The following lines should help.

``` bash
wget https://github.com/dreal/dreal3/releases/download/v3.15.06/dReal-3.15.06-linux-shared-libs.tar.gz
tar xvfz dReal-3.15.06-linux-shared-libs.tar.gz
cd dReal-3.15.06-linux/lib
export LD_LIBRARY_PATH=`pwd`
```

If it doesn't work, please let us know. If it works, please let us know as well ;-)

**Comment by evanthebouncy** [comment]
julia> using dReal

julia> x = Var(Int,"x")
Ex{Int64}(Ptr{Void} @0x00000000078e4fe0,Set{ASCIIString}({"x"}))

julia> y = Var(Int,"y")
Ex{Int64}(Ptr{Void} @0x0000000008a556a0,Set{ASCIIString}({"y"}))

julia> add!((x > 2) & (y < 10) & (x + 2*y == 7))
Set{ASCIIString}({"x","y"})

julia> is_satisfiable()
true

works the charm. thanks!!

**Comment by soonhokong** [comment]
Great!
