### ISSUE TITLE
Getting incorrect results - did I model this incorrectly?

### ISSUE THREAD

**Issue by sbromberger** [dreal/DReal.jl#19]
The problem description and code that produces the correct solution is at https://gist.github.com/sbromberger/252b011d628d20c21afb.

The implementation using DReal is at https://gist.github.com/sbromberger/1b982453ce5497c88b80

I get the following result:

```
julia> @time is_satisfiable()
944.193124 seconds (1.82 k allocations: 99.145 KB)
false
```

The correct solution is

```
[a,b,c,d,e,f,g,h,j,k,l,m,n,p,q,r] == [9,12,16,15,11,2,1,10,4,3,6,8,5,7,13,14]
```

**Comment by scungao** [comment]
Thanks a lot. We'll look into this.  

One comment (which is not the problem here): if possible please avoid using negations of equalities. We mainly work over real numbers, and in our framework (delta-complete decisions) the solver can discard "zero-measure constraints." Indeed, when `x` and `y` are real-valued, then `x!=y` can be discarded, because _numerically_ we can't always tell their difference (and in our framework this is ok). 

When the variables are integers it's of course a different story, and we should have better support for that. But for now, it'd be better to write something like 
`(x-y)^2>0.5`
just so that `x` and `y` are far apart.

**Comment by sbromberger** [comment]
Thanks. I'll make those changes and will let you know what happens. I appreciate the help.

**Comment by sbromberger** [comment]
as you predicted, no change:

```
julia> @time is_satisfiable()
991.145384 seconds (1.82 k allocations: 99.145 KB)
false
```

second gist is updated with the code I used.

**Comment by soonhokong** [comment]
@sbromberger, thanks for the report again. I'll take a look.

**Comment by soonhokong** [comment]
Closed by https://github.com/dreal/dreal3/commit/21ead3abc0b16b525c9952f9c1c1d7d38f0f37b4

**Comment by sbromberger** [comment]
I just did a `Pkg.checkout("DReal")` and reran things, but without any change:

```
julia> @time is_satisfiable()
977.232370 seconds (1.68 k allocations: 88.820 KB)
false
```

Is there a dependency I'm missing?

**Comment by soonhokong** [comment]
Dear @sbromberger,

Could you try the following?

``` julia
Pkg.checkout("DReal")
Pkg.build("DReal")
```

and test it again?

**Comment by soonhokong** [comment]
@zenna, one day you told me that we had this problem because these changes aren't tagged and added to the julia package. What can I do to tag and add the changes to the Julia package?

**Comment by sbromberger** [comment]
@soonhokong got it; thanks - will test now and update in approx 17 mins :)

**Comment by soonhokong** [comment]
@sbromberger, :+1:

**Comment by sbromberger** [comment]
Sorry for the delay. It works, and with a speed boost as well!

```
julia> @time is_satisfiable()
565.651828 seconds (1.82 k allocations: 99.145 KB)
true

julia> model(a,b,c,d,e,f,g,h,j,k,l,m,n,p,q,r)
([9 9],[12 12],[16 16],[15 15],[11 11],[2 2],[1 1],[10 10],[4 4],[3 3],[6 6],[8 8],[5 5],[7 7],[13 13],[14 14])
```

**Comment by scungao** [comment]
Great! :)

**Comment by sbromberger** [comment]
(though I'm puzzled by the output. Why is it a tuple of 1x2 Arrays? There's only one solution.)

**Comment by soonhokong** [comment]
In general, it returns an interval `[a, b]` for a variable `x`, which implies that there is solution x satisfying `a <= x <= b`. In this case, it's a special case where `a == b` and it represents a point.

**Comment by sbromberger** [comment]
That's awesome - thank you for the explanation.

**Comment by zenna** [comment]
Soonho to tag and publish a new release you need to do `Pkg.tag("DReal")` and `Pkg.publish("DReal")` then someone will review it and make then if its good accept the changes.

**Comment by soonhokong** [comment]
@zenna, thanks a lot!
