### ISSUE TITLE
Another inconsistency?

### ISSUE THREAD

**Issue by sbromberger** [dreal/DReal.jl#20]
```
a = Var(Int)
b = Var(Int)
c = Var(Int)

add!(((a^b) * c + 10*a + b) == 1)
add!((a < 10) & (b < 10))
add!(c == 5)


is_satisfiable()
false
```

but (0, 1, 5) is a solution.

**Comment by scungao** [comment]
Yes there must be bugs in handling integers. We'll look into it.

**Comment by sbromberger** [comment]
Thanks. Feel free to close this out if you have what you need in #19.

**Comment by soonhokong** [comment]
@sbromberger, thanks for the report. I'll take a look at this problem.

**Comment by soonhokong** [comment]
@sbromberger, we found that there is a problem in handling `a^b` in one of constraint solvers that we're using. I just patched the problem. I'll run regression tests and release a new version if my patch doesn't break any tests.

**Comment by soonhokong** [comment]
closed by https://github.com/dreal-deps/ibex-lib/commit/666b902024137663bcf841363c19bea29e833602
