### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by dvij** [dreal/DReal.jl#22]
Hi,
I just installed dreal (using the instructions here: http://dreal.github.io/) and DReal.jl  (using the instructions at https://github.com/dreal/DReal.jl) and the installation went smooth. However, when I tried using DReal, I got a bunch of errors:
ERROR: LoadError: LoadError: UndefVarError: model not defined
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
 in require at /Applications/Julia-0.4.5.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/dvij/.julia/v0.4/DReal/src/SolverInterface.jl, in expression starting on line 42
while loading /Users/dvij/.julia/v0.4/DReal/src/DReal.jl, in expression starting on line 84

I'm using MacOSX El Capitan on a 64 bit MacBook Pro.

Any ideas on how to fix this?

Thanks,
Dj

**Comment by soonhokong** [comment]
@dvij, thanks for the report. I'll take care of this today.

**Comment by scungao** [comment]
Hi Dj, you could also try the C++ API -- we should document it more but here's a brief intro. You would just need the dReal dynamic library (directly from [the releases page](https://github.com/dreal/dreal3/releases)) and a single header file "dreal.hh" in the src/api directory of the main dreal3 repository (".hh" is the C++ API, ".h" is the C API). For a small example take a look at [test.cpp](https://github.com/dreal/dreal3/blob/master/examples/test.cpp), and you can find more complicated examples in the same directory. The API is still quick-and-dirty for now so if anything weird comes up just let us know.
