### ISSUE TITLE
Dreal (not found in project, manifest or registry)

### ISSUE THREAD

**Issue by ssantus** [dreal/DReal.jl#28]
Hi, I want to add DReal in julia but the package manager couldn't find it: 
(@v1.5) pkg> add DReal
ERROR: The following package names could not be resolved:
 * DReal (not found in project, manifest or registry)

-----------------------------
Info about my environment:

julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 4

**Comment by soonho-tri** [comment]
I don't think we provide an up-to-date Julia binding for now. Note that this repository was written by Zenna Tavares and was using dReal3 which is not maintained anymore (now there is dReal4). 

I have zero experiences in Julia. But it seems that one can write a Julia binding using https://github.com/JuliaInterop/libcxxwrap-julia. FYI, here is an example: https://github.com/Z3Prover/z3/blob/master/src/api/julia/z3jl.cpp. This is mostly a note to my future self.

**Comment by ssantus** [comment]
I was afraid to hear something like that :(
Thanks for the answer anyways!
