### ISSUE TITLE
publish the package in the official Package system

### ISSUE THREAD

**Issue by soonhokong** [dreal/DReal.jl#9]
A reference: https://github.com/JuliaLang/BinDeps.jl

FYI, dReal.jl requires the following five shared libraries now:
- libprim.so : [filibxx](https://github.com/dreal-deps/filibxx/), LGPL2
- libClp.so: [Coin-or Linear Programming](https://github.com/dreal-deps/clp-1.16), EPL
- libibex.so : [IBEX](https://github.com/dreal-deps/ibex-lib), LGPL3
- libcapd.so : [CAPD4.0](https://github.com/dreal-deps/capdDynSys-4.0), GPL3
- libdreal.so : [dReal](https://github.com/dreal/dreal3), GPL3

**Comment by zenna** [comment]
Let's do this.

**Comment by zenna** [comment]
I have automated the dependency-grabbing.  I tired with BinDeps for a while but it's confusing and maybe overkill, so I just automated the downloading, etc.

**Comment by soonhokong** [comment]
Thanks! I'll test it tomorrow.

**Comment by zenna** [comment]
I'm gonna tag this and publish it the package manager

**Comment by soonhokong** [comment]
Great!
